events {
    worker_connections 1024;
}

http {
    upstream flask_cluster {
        # This directly points to the two independent containers spun up by docker-compose!
        server web_1:5000;
        server web_2:5000;
    }

    server {
        # Nginx globally listens perfectly on port 80 (HTTP)
        listen 80;

        location / {
            # Bounces incoming traffic evenly back and forth across web_1 and web_2
            proxy_pass http://flask_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
